---

- name: Minio | Download minio cli
  ansible.builtin.get_url:
    url: "https://dl.min.io/client/mc/release/linux-{{ [ansible_architecture] | map('extract', minio_deb_architecture) | first }}/mc"
    dest: /usr/local/bin/mc
    owner: root
    group: root
    mode: 0755

...
