---
configs:
  memory: "2048"
  cpus: "2"
  # if a specific ansible version has to be used, this can be changed from latest to e.g. "2.11.0"
  ansible_version: "latest"
  role_name: "ansible-role-minio_cli"
  ip: 192.168.56.54
  domain: minio-cli.lokal
  aliases: []

...
