---
- name: Converge
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  tasks:
  - name: Include andrelohmann.minio_cli
    ansible.builtin.include_role:
      name: "andrelohmann.minio_cli"
...
